<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testGuard" nsURI="http://www.igesila.com/testGuard/0.1" nsPrefix="testGuard">
  <eClassifiers xsi:type="ecore:EClass" name="TestGuard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestMethod" eType="#//RequestMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Headers" eType="#//Headers"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Params" eType="#//Params"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestBody" eType="#//RequestBody"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestGuardModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Unit" upperBound="-1" eType="#//TestGuardUnit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestGuardUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestMethod" eType="#//RequestMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequestMethod">
    <eLiterals name="POST" literal="POST"/>
    <eLiterals name="PUT" value="1" literal="PUT"/>
    <eLiterals name="GET" value="2" literal="GET"/>
    <eLiterals name="DELETE" value="3" literal="DELETE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Headers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Header" upperBound="-1"
        eType="#//Header" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Params">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Param" upperBound="-1"
        eType="#//Param" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EntityHeaderFields">
    <eLiterals name="Allow"/>
    <eLiterals name="ContentEncoding" value="1" literal="Content-Encoding"/>
    <eLiterals name="ContentLanguage" value="2" literal="Content-Language"/>
    <eLiterals name="ContentLength" value="3" literal="Content-Length"/>
    <eLiterals name="ContentLocation" value="4" literal="Content-Location"/>
    <eLiterals name="ContentMD5" value="5" literal="Content-MD5"/>
    <eLiterals name="ContentRange" value="6" literal="Content-Range"/>
    <eLiterals name="ContentType" value="7" literal="Content-Type">
      <eAnnotations source="ExtendedMetaData" references="http://www.eclipse.org/emf/2002/Ecore#//EString/%http:%2F%2F%2Forg%2Feclipse%2Femf%2Fecore%2Futil%2FExtendedMetaData%">
        <details key="desc" value="实体主体内对象的媒体类型"/>
        <details key="content" value="application/json|application/xml"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Expires" value="8"/>
    <eLiterals name="LastModified" value="9" literal="Last-Modified"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Method">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="UPDATE" value="2"/>
  </eClassifiers>
</ecore:EPackage>
